# Generated by Django 5.1.7 on 2025-05-28 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Придумайте имя своему дереву', max_length=250, null=True, verbose_name='Наименование')),
                ('type_of_tree', models.CharField(choices=[('pine', 'Сосна'), ('birch', 'Береза'), ('oak', 'Дуб')], help_text='Выберите вид своего дерева', max_length=5, verbose_name='Вид дерева')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время посадки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'дерево',
                'verbose_name_plural': 'деревья',
            },
        ),
    ]
